version: "3.9"
services:
  app1:
    build: ./go1.19.3
    container_name: rp-app1
  app2:
    build: ./go1.19.3
    container_name: rp-app2
  app3:
    build: ./go1.19.3
    container_name: rp-app3
  nginx:
    image: "nginx"
    container_name: rp-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    links:
      - app1
      - app2
      - app3
